version: "3.8"

services:
  db:
    image: postgres:15.0
    container_name: db
    env_file: ./.env
#    ports:
#      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1111
      - POSTGRES_DB=$POSTGRES_DB
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    depends_on:
      - db
    image: dominskyi/rick-and-morty
    build:
        context: .
    container_name: app
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1111
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#      SPRING_APPLICATION_JSON: '{
#        "spring.datasource.url" : "jdbc:postgresql://postgres:$POSTGRES_DOCKER_PORT/$POSTGRES_DB",
#        "spring.datasource.username" : "$POSTGRES_USER",
#        "spring.datasource.password" : "$POSTGRES_PASSWORD"
#      }'
#      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
